version: '3'

services:
  mongodb-server:
    image: "mongo"
    restart: "always"
    volumes:
      - ./infrasight-data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: mongo
  
  infrasight-discovery-service:
    build: 
      context: "./infrasight-discovery-service"
      dockerfile: "Dockerfile"
    restart: "always"

  infrasight-auth-service:
    build: 
      context: "./infrasight-auth-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-presentation-service:
    build: 
      context: "./infrasight-presentation-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-prophet-service:
    build: 
      context: "./infrasight-prophet-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
  
  infrasight-ml-service:
    build: 
      context: "./infrasight-ml-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
  
  infrasight-server-service:
    build: 
      context: "./infrasight-server-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-prophet-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-stats-capture-service:
    build: 
      context: "./infrasight-stats-capture-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-ml-service
      - infrasight-prophet-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
  
  infrasight-gatewsy-service:
    build: 
      context: "./infrasight-gatewsy-service"
      dockerfile: "Dockerfile"
    ports:
      - 8016:8016
    restart: "unless-stopped"
    depends_on:
      - infrasight-auth-service
      - infrasight-presentation-service
      - infrasight-server-service
      - infrasight-stats-capture-service
    environment:
      SERVER_PORT: 8016
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
