version: '3'

services:
  mongodb-server:
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: mongo
  
  infrasight-discovery-service:
    build: 
      context: "./infrasight-discovery-service"
      dockerfile: "Dockerfile"
    ports:
      - 8010:8010
    restart: "always"

  infrasight-auth-service:
    build: 
      context: "./infrasight-auth-service"
      dockerfile: "Dockerfile"
    ports:
      - 8011:8011
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      SERVER_PORT: 8011
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-presentation-service:
    build: 
      context: "./infrasight-presentation-service"
      dockerfile: "Dockerfile"
    ports:
      - 8012:8012
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      SERVER_PORT: 8012
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-prophet-service:
    build: 
      context: "./infrasight-prophet-service"
      dockerfile: "Dockerfile"
    ports:
      - 8013:8013
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    environment:
      SERVER_PORT: 8013
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
  
  infrasight-server-service:
    build: 
      context: "./infrasight-server-service"
      dockerfile: "Dockerfile"
    ports:
      - 8014:8014
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-prophet-service
    environment:
      SERVER_PORT: 8014
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-stats-capture-service:
    build: 
      context: "./infrasight-stats-capture-service"
      dockerfile: "Dockerfile"
    ports:
      - 8015:8015
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-server-service
    environment:
      SERVER_PORT: 8015
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
  
  infrasight-gatewsy-service:
    build: 
      context: "./infrasight-gatewsy-service"
      dockerfile: "Dockerfile"
    ports:
      - 8016:8016
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-stats-capture-service
    environment:
      SERVER_PORT: 8016
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
