version: '3.4'

services:
  mongodb-server:
    image: "mongo"
    restart: "always"
    volumes:
      - ./infrasight-data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_ROOT_USERNAME: mongo
  
  infrasight-discovery-service:
    build: 
      context: "./infrasight-discovery-service"
      dockerfile: "Dockerfile"
    restart: "always"

  infrasight-auth-service:
    build: 
      context: "./infrasight-auth-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-presentation-service:
    build: 
      context: "./infrasight-presentation-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-prophet-service:
    build: 
      context: "./infrasight-prophet-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_MAIL_USERNAME: 
      SPRING_MAIL_PASSWORD: 

  infrasight-ml-service:
    build: 
      context: "./infrasight-ml-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
  
  infrasight-server-service:
    build: 
      context: "./infrasight-server-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-prophet-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-stats-capture-service:
    build: 
      context: "./infrasight-stats-capture-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-ml-service
      - infrasight-prophet-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw
  
  infrasight-gatewsy-service:
    build: 
      context: "./infrasight-gatewsy-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      infrasight-auth-service:
        condition: service_healthy
      infrasight-presentation-service:
        condition: service_healthy
      infrasight-server-service:
        condition: service_healthy
      infrasight-stats-capture-service:
        condition: service_healthy
    environment:
      SERVER_PORT: 8016
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: mongodb-server
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: mongopw

  infrasight-ui-service:
    build: 
      context: "./infrasight-ui-service"
      dockerfile: "Dockerfile"
    restart: "unless-stopped"
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      infrasight-gatewsy-service:
        condition: service_healthy

  infrasight-nginix:
    build:
      context: ./infrasight-nginx
      dockerfile: "Dockerfile"
    depends_on:
      infrasight-ui-service:
        condition: service_healthy
    restart: always
    ports:
      - "8080:80"