version: '3.4'

services:
  mongodb-server:
    image: "mongo"
    restart: "always"
    volumes:
      - ./infrasight-data:/data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PWD
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
  
  infrasight-discovery-service:
    image: navin3d/eureka-discovery
    restart: "always"

  infrasight-auth-service:
    image: navin3d/infrasight-auth-service
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: $MONGO_HOST
      SPRING_DATA_MONGODB_PORT: $MONGO_PORT
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PWD

  infrasight-presentation-service:
    image: navin3d/infrasight-presentation-service
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: $MONGO_HOST
      SPRING_DATA_MONGODB_PORT: $MONGO_PORT
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PWD

  infrasight-prophet-service:
    image: navin3d/prophet-service
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-discovery-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_MAIL_USERNAME: $EMAIL_ADDRESS
      SPRING_MAIL_PASSWORD: $EMAIL_PASSWORD
  
  infrasight-ml-service:
    image: navin3d/infrasight-ml-service
    restart: "unless-stopped"
    depends_on:
      - infrasight-discovery-service
    environment:
      EUREKA_HOST: infrasight-discovery-service
  
  infrasight-server-service:
    image: navin3d/infrasight-server-service
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-prophet-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: $MONGO_HOST
      SPRING_DATA_MONGODB_PORT: $MONGO_PORT
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PWD

  infrasight-stats-capture-service:
    image: navin3d/infrasight-stats-capture-service
    restart: "unless-stopped"
    depends_on:
      - mongodb-server
      - infrasight-ml-service
      - infrasight-prophet-service
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: $MONGO_HOST
      SPRING_DATA_MONGODB_PORT: $MONGO_PORT
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PWD
  
  infrasight-gatewsy-service:
    image: navin3d/infrasight-gatewsy-service
    restart: "unless-stopped"
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      infrasight-auth-service:
        condition: service_healthy
      infrasight-presentation-service:
        condition: service_healthy
      infrasight-server-service:
        condition: service_healthy
      infrasight-stats-capture-service:
        condition: service_healthy
    environment:
      SERVER_PORT: 8016
      EUREKA_HOST: infrasight-discovery-service
      SPRING_DATA_MONGODB_HOST: $MONGO_HOST
      SPRING_DATA_MONGODB_PORT: $MONGO_PORT
      SPRING_DATA_MONGODB_USERNAME: $MONGO_USER
      SPRING_DATA_MONGODB_PASSWORD: $MONGO_PWD

  infrasight-ui-service:
    image: navin3d/infrasight-ui-service
    restart: "unless-stopped"
    healthcheck:
      test: "exit 0"
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      infrasight-gatewsy-service:
        condition: service_healthy

  infrasight-nginix:
    image: navin3d/infrasight-nginx
    depends_on:
      infrasight-ui-service:
        condition: service_healthy
    restart: always
    ports:
      - "8080:80"
